services:
  postgres:
    image: postgres:16-alpine
    container_name: geo-world-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geo_world_manager
    ports:
      - "5432:5432"
    volumes:
      - geo_world_data:/var/lib/postgresql/data

volumes:
  geo_world_data:
